# Phase T2 of docs/en/monitoring-design.md: a VPC Lambda that polls the ONTAP
# REST API of one FSx for ONTAP file system and publishes CloudWatch custom
# metrics for qtree quotas and SnapMirror health and lag, with alarms.
#
# Metric names, dimensions and alarms follow the "Metric catalog" and "Alert
# design" sections of docs/en/monitoring-design.md. The Lambda source is
# shared/lambda/ontap_metrics/; qtree_quota_poller.py there is also the inline
# code of shared/templates/qtree-quota-monitor.yaml (generated by
# shared/scripts/sync-inline-lambda.py), so both deployment paths run one file.
#
# SnapMirror fields come from the ONTAP 9.18.1 REST API reference:
#   https://docs.netapp.com/us-en/ontap-restapi-9181/get-snapmirror-relationships.html
# The collector polls the destination file system.

data "aws_region" "current" {}
data "aws_partition" "current" {}

locals {
  region    = data.aws_region.current.region
  partition = data.aws_partition.current.partition

  collector_namespaces = {
    qtree      = "FSxONTAP/Qtree"
    snapmirror = "FSxONTAP/SnapMirror"
  }
  collectors = concat(
    var.enable_qtree_collector ? ["qtree"] : [],
    var.enable_snapmirror_collector ? ["snapmirror"] : [],
  )
  namespaces = [for c in local.collectors : local.collector_namespaces[c]]

  # EventBridge requires the singular unit for a value of 1.
  schedule_expression = var.poll_interval_minutes == 1 ? "rate(1 minute)" : "rate(${var.poll_interval_minutes} minutes)"
  # At least one poll lands in every period. At the default interval (5) this
  # is the template's fixed 300 seconds.
  alarm_period = max(300, var.poll_interval_minutes * 60)

  create_sns    = var.notification_email != ""
  alarm_actions = local.create_sns ? [aws_sns_topic.alarm[0].arn] : []

  endpoint_services = toset(concat(
    var.create_monitoring_endpoint ? ["monitoring"] : [],
    var.create_secretsmanager_endpoint ? ["secretsmanager"] : [],
  ))
  create_endpoints = length(local.endpoint_services) > 0

  function_name  = "${var.name_prefix}-poller"
  log_group_name = "/aws/lambda/${local.function_name}"

  # Only the secret ARN is passed; the handler reads the password at run time.
  lambda_env = merge(
    {
      ONTAP_MGMT_IP                 = var.ontap_management_ip
      ONTAP_CREDENTIALS_SECRET_ARN  = var.ontap_credentials_secret_arn
      FILE_SYSTEM_ID                = var.file_system_id
      COLLECTORS                    = join(",", local.collectors)
      SNAPMIRROR_MAX_RELATIONSHIPS  = tostring(var.snapmirror_max_relationships)
      CREDENTIALS_CACHE_TTL_SECONDS = "300"
      CA_CERT_PATH                  = var.ca_cert_path
    },
    var.enable_qtree_collector ? { SVM_NAME = var.qtree_svm_name } : {},
  )
}

# ----------------------------------------------------------------
# Lambda package, built at plan time from the shared source directory
# ----------------------------------------------------------------
# With a //subdirectory git or archive source, Terraform extracts the whole
# package, so ../../shared resolves. A sparse checkout must include
# shared/lambda/ontap_metrics (see "Obtaining the module" in the README).
data "archive_file" "lambda" {
  type        = "zip"
  source_dir  = "${path.module}/../../shared/lambda/ontap_metrics"
  output_path = "${path.module}/.build/ontap-metrics-lambda.zip"
  # Same checksum on every platform, so a plan from another OS shows no diff.
  output_file_mode = "0666"
  excludes = [
    "tests",
    "tests/**",
    "__pycache__",
    "__pycache__/**",
    "**/__pycache__",
    "**/__pycache__/**",
  ]
}

# ----------------------------------------------------------------
# Logs, dead-letter queue, IAM
# ----------------------------------------------------------------
resource "aws_cloudwatch_log_group" "poller" {
  name              = local.log_group_name
  retention_in_days = var.log_retention_days
  tags              = var.tags
}

# The schedule invokes the function asynchronously, so a failing invocation is
# retried twice by Lambda and then lands here (dlq_depth alarm).
resource "aws_sqs_queue" "dlq" {
  name                      = "${var.name_prefix}-dlq"
  message_retention_seconds = 1209600
  kms_master_key_id         = "alias/aws/sqs"
  tags                      = var.tags
}

resource "aws_iam_role" "lambda" {
  name = "${var.name_prefix}-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = var.tags
}

# ENI management for the VPC attachment, as in the CloudFormation template.
resource "aws_iam_role_policy_attachment" "vpc_access" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:${local.partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

# jsonencode rather than data "aws_iam_policy_document": a mock provider
# returns a random string for data sources, which would leave the offline
# tests nothing to assert on.
resource "aws_iam_role_policy" "lambda" {
  name = "${var.name_prefix}-policy"
  role = aws_iam_role.lambda.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      [
        {
          Sid      = "SecretsRead"
          Effect   = "Allow"
          Action   = "secretsmanager:GetSecretValue"
          Resource = var.ontap_credentials_secret_arn
        },
      ],
      var.ontap_credentials_kms_key_arn == null ? [] : [
        {
          Sid      = "SecretKms"
          Effect   = "Allow"
          Action   = "kms:Decrypt"
          Resource = var.ontap_credentials_kms_key_arn
          Condition = {
            StringEquals = { "kms:ViaService" = "secretsmanager.${local.region}.amazonaws.com" }
          }
        },
      ],
      [
        {
          # PutMetricData has no resource-level permissions; the namespace
          # condition limits it to the enabled collectors' namespaces.
          Sid       = "CloudWatchPublish"
          Effect    = "Allow"
          Action    = "cloudwatch:PutMetricData"
          Resource  = "*"
          Condition = { StringEquals = { "cloudwatch:namespace" = local.namespaces } }
        },
        {
          Sid      = "Logs"
          Effect   = "Allow"
          Action   = ["logs:CreateLogStream", "logs:PutLogEvents"]
          Resource = "${aws_cloudwatch_log_group.poller.arn}:*"
        },
        {
          Sid      = "DeadLetterQueue"
          Effect   = "Allow"
          Action   = "sqs:SendMessage"
          Resource = aws_sqs_queue.dlq.arn
        },
      ],
    )
  })
}

# ----------------------------------------------------------------
# Network: Lambda security group and optional interface endpoints
# ----------------------------------------------------------------
# No inline rules. The AWS provider removes the default allow-all egress rule
# of a new VPC security group, so only the egress rules below apply. The file
# system's own security group is not modified; the README gives the ingress
# rule to add there (source: this group, output lambda_security_group_id).
resource "aws_security_group" "lambda" {
  name        = "${var.name_prefix}-lambda"
  description = "FSx for ONTAP custom-metrics poller: HTTPS to the ONTAP management endpoint and to AWS APIs"
  vpc_id      = var.vpc_id
  tags        = merge(var.tags, { Name = "${var.name_prefix}-lambda" })
}

resource "aws_vpc_security_group_egress_rule" "ontap_management" {
  security_group_id = aws_security_group.lambda.id
  description       = "ONTAP REST API on the file system management endpoint"
  cidr_ipv4         = "${var.ontap_management_ip}/32"
  ip_protocol       = "tcp"
  from_port         = 443
  to_port           = 443
  tags              = var.tags
}

resource "aws_vpc_security_group_egress_rule" "aws_api" {
  for_each = toset(var.aws_api_egress_cidr_blocks)

  security_group_id = aws_security_group.lambda.id
  description       = "CloudWatch and Secrets Manager over a NAT gateway or existing interface endpoints"
  cidr_ipv4         = each.value
  ip_protocol       = "tcp"
  from_port         = 443
  to_port           = 443
  tags              = var.tags
}

resource "aws_security_group" "endpoints" {
  count = local.create_endpoints ? 1 : 0

  name        = "${var.name_prefix}-endpoints"
  description = "Interface endpoints for the FSx for ONTAP custom-metrics poller"
  vpc_id      = var.vpc_id
  tags        = merge(var.tags, { Name = "${var.name_prefix}-endpoints" })
}

resource "aws_vpc_security_group_ingress_rule" "endpoints_from_lambda" {
  count = local.create_endpoints ? 1 : 0

  security_group_id            = aws_security_group.endpoints[0].id
  description                  = "HTTPS from the poller"
  referenced_security_group_id = aws_security_group.lambda.id
  ip_protocol                  = "tcp"
  from_port                    = 443
  to_port                      = 443
  tags                         = var.tags
}

resource "aws_vpc_security_group_egress_rule" "lambda_to_endpoints" {
  count = local.create_endpoints ? 1 : 0

  security_group_id            = aws_security_group.lambda.id
  description                  = "HTTPS to the module-created interface endpoints"
  referenced_security_group_id = aws_security_group.endpoints[0].id
  ip_protocol                  = "tcp"
  from_port                    = 443
  to_port                      = 443
  tags                         = var.tags
}

# An interface endpoint with private DNS for a service conflicts with an
# existing one for the same service in the VPC; keep create_*_endpoint false
# when shared/scripts/preflight-check.sh reports one.
resource "aws_vpc_endpoint" "this" {
  for_each = local.endpoint_services

  vpc_id              = var.vpc_id
  service_name        = "com.amazonaws.${local.region}.${each.key}"
  vpc_endpoint_type   = "Interface"
  subnet_ids          = var.subnet_ids
  security_group_ids  = [aws_security_group.endpoints[0].id]
  private_dns_enabled = true
  tags                = merge(var.tags, { Name = "${var.name_prefix}-${each.key}" })
}

# ----------------------------------------------------------------
# Lambda function and schedule
# ----------------------------------------------------------------
resource "aws_lambda_function" "poller" {
  function_name    = local.function_name
  description      = "Polls the ONTAP REST API of ${var.file_system_id} and publishes ${join(", ", local.namespaces)} metrics"
  role             = aws_iam_role.lambda.arn
  runtime          = "python3.12"
  handler          = "ontap_metrics_handler.lambda_handler"
  filename         = data.archive_file.lambda.output_path
  source_code_hash = data.archive_file.lambda.output_base64sha256
  memory_size      = 256
  # Same budget as the template: up to 50 report pages plus up to 1,501
  # sequential PutMetricData calls for a large SVM, each ONTAP request with a
  # 30-second timeout.
  timeout = 300
  # Single-flight: one poller at a time. A run can take up to the 300-second
  # timeout and Lambda retries a failed asynchronous run, so with a short
  # poll_interval_minutes two runs could overlap; each execution environment
  # has its own credential cache and would send its own login, so a rejected
  # password would be retried in parallel. An overlapping invocation is
  # throttled instead, and Lambda requeues it (up to 6 hours, then the DLQ).
  reserved_concurrent_executions = 1
  layers                         = var.ca_cert_layer_arn == "" ? [] : [var.ca_cert_layer_arn]

  vpc_config {
    subnet_ids         = var.subnet_ids
    security_group_ids = [aws_security_group.lambda.id]
  }

  dead_letter_config {
    target_arn = aws_sqs_queue.dlq.arn
  }

  environment {
    variables = local.lambda_env
  }

  tags = var.tags

  depends_on = [
    aws_cloudwatch_log_group.poller,
    aws_iam_role_policy.lambda,
    aws_iam_role_policy_attachment.vpc_access,
  ]
}

resource "aws_cloudwatch_event_rule" "schedule" {
  name                = "${var.name_prefix}-schedule"
  description         = "Poll the ONTAP REST API of ${var.file_system_id} every ${var.poll_interval_minutes} minute(s)"
  schedule_expression = local.schedule_expression
  state               = "ENABLED"
  tags                = var.tags
}

resource "aws_cloudwatch_event_target" "poller" {
  rule      = aws_cloudwatch_event_rule.schedule.name
  target_id = "ontap-metrics-poller"
  arn       = aws_lambda_function.poller.arn
}

resource "aws_lambda_permission" "schedule" {
  statement_id  = "AllowEventBridgeSchedule"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.poller.function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.schedule.arn
}

# ----------------------------------------------------------------
# SNS topic for alarms (only when notification_email is set)
# ----------------------------------------------------------------
# Unencrypted, as in the dashboard module and the CloudFormation template.
resource "aws_sns_topic" "alarm" {
  count = local.create_sns ? 1 : 0

  name         = "${var.name_prefix}-alarms"
  display_name = "FSx for ONTAP custom metrics (${var.file_system_id})"
  tags         = var.tags
}

resource "aws_sns_topic_subscription" "email" {
  count = local.create_sns ? 1 : 0

  topic_arn = aws_sns_topic.alarm[0].arn
  protocol  = "email"
  endpoint  = var.notification_email
}

# ----------------------------------------------------------------
# Alarms (docs/en/monitoring-design.md "Alert design")
# ----------------------------------------------------------------
# Same alarm as the template's QtreeQuotaAlarm, which reads the SVM-level
# maximum because CloudWatch treats each dimension set as a separate metric.
resource "aws_cloudwatch_metric_alarm" "qtree_quota" {
  count = var.enable_qtree_collector ? 1 : 0

  alarm_name          = "${var.name_prefix}-qtree-quota-high"
  alarm_description   = "One or more qtrees on SVM ${var.qtree_svm_name} exceeded ${var.qtree_quota_threshold_percent}% quota usage. Find which from the per-qtree QtreeQuotaUsedPercent metric (namespace FSxONTAP/Qtree, dimensions SvmName, VolumeName, QtreeName). Consider expanding the quota, archiving data, or FabricPool tiering for cold data."
  namespace           = "FSxONTAP/Qtree"
  metric_name         = "QtreeQuotaUsedPercentMax"
  dimensions          = { SvmName = var.qtree_svm_name }
  statistic           = "Maximum"
  period              = local.alarm_period
  evaluation_periods  = 2
  threshold           = var.qtree_quota_threshold_percent
  comparison_operator = "GreaterThanThreshold"
  # missing: an SVM without tree quotas publishes no maximum and must not
  # alarm permanently; a stopped poller is caught by the heartbeat alarm.
  treat_missing_data = "missing"
  alarm_actions      = local.alarm_actions
  ok_actions         = local.alarm_actions
  tags               = var.tags
}

resource "aws_cloudwatch_metric_alarm" "snapmirror_unhealthy" {
  count = var.enable_snapmirror_collector ? 1 : 0

  alarm_name          = "${var.name_prefix}-snapmirror-unhealthy"
  alarm_description   = "One or more SnapMirror relationships whose destination is ${var.file_system_id} report healthy = false. Find which from SnapMirrorRelationshipHealthy (namespace FSxONTAP/SnapMirror, dimensions FileSystemId, SourcePath, DestinationPath); the poller log lists unhealthy_reason codes."
  namespace           = "FSxONTAP/SnapMirror"
  metric_name         = "SnapMirrorUnhealthyCount"
  dimensions          = { FileSystemId = var.file_system_id }
  statistic           = "Maximum"
  period              = local.alarm_period
  evaluation_periods  = 2
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "missing"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions
  tags                = var.tags
}

resource "aws_cloudwatch_metric_alarm" "snapmirror_lag" {
  count = var.enable_snapmirror_collector ? 1 : 0

  alarm_name          = "${var.name_prefix}-snapmirror-lag-high"
  alarm_description   = "The largest SnapMirror lag on destination ${var.file_system_id} exceeded ${var.snapmirror_lag_threshold_seconds} seconds. Find which relationship from SnapMirrorLagSeconds (namespace FSxONTAP/SnapMirror, dimensions FileSystemId, SourcePath, DestinationPath)."
  namespace           = "FSxONTAP/SnapMirror"
  metric_name         = "SnapMirrorLagSecondsMax"
  dimensions          = { FileSystemId = var.file_system_id }
  statistic           = "Maximum"
  period              = local.alarm_period
  evaluation_periods  = 1
  threshold           = var.snapmirror_lag_threshold_seconds
  comparison_operator = "GreaterThanThreshold"
  # missing: no relationship with a parseable lag_time publishes no maximum.
  treat_missing_data = "missing"
  alarm_actions      = local.alarm_actions
  ok_actions         = local.alarm_actions
  tags               = var.tags
}

# breaching: a poller that stops publishing (no route, throttling, deleted
# schedule) must alarm, not go quiet.
resource "aws_cloudwatch_metric_alarm" "heartbeat" {
  for_each = toset(local.collectors)

  alarm_name          = "${var.name_prefix}-${each.key}-heartbeat"
  alarm_description   = "The ${each.key} collector on ${var.file_system_id} failed or stopped reporting (CollectorSucceeded < 1 or missing). Check the ${local.log_group_name} log group; ONTAP reachability and credentials are the usual causes."
  namespace           = local.collector_namespaces[each.key]
  metric_name         = "CollectorSucceeded"
  dimensions          = { FileSystemId = var.file_system_id, Collector = each.key }
  statistic           = "Minimum"
  period              = local.alarm_period
  evaluation_periods  = 2
  threshold           = 1
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "breaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions
  tags                = var.tags
}

resource "aws_cloudwatch_metric_alarm" "dlq_depth" {
  alarm_name          = "${var.name_prefix}-dlq-depth"
  alarm_description   = "The ONTAP custom-metrics poller failed all retries and the invocation landed in ${aws_sqs_queue.dlq.name}. Custom metrics are stale. Check the ${local.log_group_name} log group."
  namespace           = "AWS/SQS"
  metric_name         = "ApproximateNumberOfMessagesVisible"
  dimensions          = { QueueName = aws_sqs_queue.dlq.name }
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions
  tags                = var.tags
}

resource "aws_cloudwatch_metric_alarm" "lambda_errors" {
  alarm_name          = "${var.name_prefix}-lambda-errors"
  alarm_description   = "The ONTAP custom-metrics poller raised an error (for example, a heartbeat could not be published). Check the ${local.log_group_name} log group."
  namespace           = "AWS/Lambda"
  metric_name         = "Errors"
  dimensions          = { FunctionName = aws_lambda_function.poller.function_name }
  statistic           = "Sum"
  period              = local.alarm_period
  evaluation_periods  = 1
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = local.alarm_actions
  ok_actions          = local.alarm_actions
  tags                = var.tags
}
